[system]
# where udrome stores its database, plugins, album art, transcoded files, etc.
data_path = "/tmp"
# TODO max cache size
cache_mb = 512
bind_addr = "localhost:3000"
# true: sets cors to allow any request - needed when frontend is served separately
# !disable this in prod!
dev = true

[indexer]
# false: useful for quick restarts (and retaining song IDs for connected clients).
enable = true

[indexer.exclude]
files = ["corrupt1.mp3", "corrupt2.mp3"]
# TODO
dirs = []

[system.profiler]
# TODO (tracing-tracy)

[system.plugins]
# TODO plugin system
media = ["oggvorbis.rhai", "mod.rhai"]

[media]
paths = ["/media/mp3z"]
